const langEN = {
    appTitle: 'React-phonebook',
    appUnderTitle: `web application that allows users to store and manage their contacts,
    providing features for adding, editing, and deleting contact information`,
    homeBtn: 'Home',
    contactsBtn: 'Contacts',
    logBtn: 'Login',
    regBtn: 'Register',
    footerTitle: 'React-Phonebook-2023',
    name: 'Name',
    email: 'Email',
    pass: 'Password',
    regSubmit: "SignUp",
    logSubmit: "SignIn",
    alreadyGot: "Already have an account?",
    notYet: "Don't have an account?",
    show: "Show",
    hide: "Hide",
    left: "seconds left",
    wasted: "Wasted",
    try: "Try again",
    phonebook: "Phonebook",
    number: "Number",
    phone: "Phone",
    find: "Find contacts by name",
    empty: "List is empty ...",
    add: "Add contact",
    edit: "EDIT",
    delete: "DELETE",
    avatar: "Avatar",
    set: "Set",
    settings: "Settings",
    out: "LogOut",
    
}


const langUA = {
    appTitle: 'React телефонна книга',
    appUnderTitle: `веб додаток, який дозволяє користувачам зберігати та керувати своїми контактами,
    надання функцій для додавання, редагування та видалення контактної інформації`,
    homeBtn: 'Головна',
    contactsBtn: 'Контакти',
    logBtn: 'Увійти',
    regBtn: 'Реєстрація',
    footerTitle: 'React-телефонна книга-2023',
    name: 'Ім’я',
    email: 'Пошта',
    pass: 'Пароль',
    regSubmit: "Зареєструватися",
    logSubmit: "Увійти",
    alreadyGot: "Вже є акаунт?",
    notYet: "Немає акаунту?",
    show: "Показати",
    hide: "Приховати",
    left: "секунд залишилося",
    wasted: "Витрачено",
    try: "Спробуйте знову",
    phonebook: "Телефонна книга",
    number: "Номер",
    phone: "Номер",
    find: "Пошук контактів за іменами",
    empty: "Список порожній...",
    add: "Додати контакт",
    edit: "РЕДАГУВАТИ",
    delete: "ВИДАЛИТИ",
    avatar: "Аватар",
    set: "Встановити",
    settings: "Налаштування",
    out: "Вийти",

}

export { langEN, langUA} // {lang.homeBtn}